### ISSUE TITLE
(ImportError: No module named 'MySQLdb') celery executor issue

### ISSUE THREAD

**Issue by Shrashti** [mumoshu/kube-airflow#29]
Hi,

I am facing below issue while running DAGS using **airflow backfill <DAG_id> -s <start_date> -e <end_date>**

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/airflow/executors/celery_executor.py", line 94, in sync
    state = task.state
  File "/usr/local/lib/python3.5/dist-packages/celery/result.py", line 431, in state
    return self._get_task_meta()['status']
  File "/usr/local/lib/python3.5/dist-packages/celery/result.py", line 370, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/base.py", line 352, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/database/__init__.py", line 53, in _inner
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/database/__init__.py", line 122, in _get_task_meta_for
    session = self.ResultSession()
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/database/__init__.py", line 99, in ResultSession
    **self.engine_options)
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/database/session.py", line 58, in session_factory
    engine, session = self.create_session(dburi, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/database/session.py", line 44, in create_session
    engine = self.get_engine(dburi, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/database/session.py", line 41, in get_engine
    return create_engine(dburi, poolclass=NullPool)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/__init__.py", line 391, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 110, in dbapi
    return __import__('MySQLdb')
ImportError: No module named 'MySQLdb'

**Comment by celestialorb** [comment]
Same issue here.  It feels like SqlAlchemy is defaulting to MySQL instead of Postgres.

**Comment by shao-shuai** [comment]
try `pip install mysql-connector-python`
and `pip install mysql`
